using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Ejemplito1;

namespace Ejemplito2{

    public class AssemblyTest2 : MonoBehaviour
    {
        public AssemblyTestBehaviour test;
        // Start is called before the first frame update
        void Start()
        {
            
        }

        // Update is called once per frame
        void Update()
        {
            
        }

        public int Suma(int a, int b)
        {
            return a + b;
        }

        public int Resta(int a, int b)
        {
            return a - b;
        }

        public int Multiplicacion(int a, int b)
        {
            return a * b;
        }

        public int Division(int a, int b)
        {
            return a / b;
        }
    }
}